### ISSUE TITLE
Add high CPU spot node pool

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#114]
We should have two seperate spot node pools, one for high mem processing jobs, one for high CPU. This enables processing jobs can select the compute that best suits its needs.

**Comment by woodcockr** [comment]
I’m going to close this issue as its not be commented on for a while and its also reaching toward the level of being a specific deployment issue. If a specific deployment wants this capability then they can add it to their live repo without difficulty. I don’t believe the ODC baseline component needs to support this.
