### ISSUE TITLE
Merge three terraform steps into a single monolithic step

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#118]
Currently we build infrastructure, deploy nodes, then deploy add ons. With the improved logic in terraform 0.12 I believe this can be merged into a single deployment step.

This should avoid some of the issues with unused variables throwing warnings and enable support for deploying this infrastructure as a terraform module instead.

- [ ] Develop as a seperate branch 
- [ ] Move directory structure (defined below)
- [ ] Rename repo to terraform-aws-odc

Directory structure
```
submodules/eks
submodules/rds
submodules/...
examples/jupyter.tf
main.tf
variables.tf
README
```

**Comment by woodcockr** [comment]
I've started work on this on the `terraform-aws-odc` branch

**Comment by woodcockr** [comment]
For information, some of the best practice in the refactor is covered in [Terraform Up and Running, 2nd Edition](http://shop.oreilly.com/product/0636920225010.do). 
It's important its the 2nd Edition as Terraform 0.12 and above is required.

**Comment by woodcockr** [comment]
It appears terraform is hardwired to look for a `modules` directory so we can't call it `submodules`
