### ISSUE TITLE
Add node local dns cache

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#121]
This should improve network issues with dask that are caused by dns

https://aws.amazon.com/blogs/containers/eks-dns-at-scale-and-spikeiness/

this should help running apps like DASK that make heavy use of dns when communicating with other pods.

**Comment by woodcockr** [comment]
This issue isn’t relevant to the terraform module repository as they can be deployed and managed by flux, so if they were to become part of the baseline ODC configuration it would be via the flux-odc-sample live repo.

For what it’s worth I’ve been running this successfully for some time, also aws-node-termination handler. These aren’t essential for the baseline operation and arguably border on becoming a live deployment choice and I’m inclined to suggest they not be part of the ODC community supplied sample setup (in flux-odc-sample). Information and support for these are readily available elsewhere.

If you disagree feel free to open a new issue in the flux-odc-sample repo and discuss
