### ISSUE TITLE
Kube2iam falls over at scale

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#122]
When running large processing jobs we need to set aws credentials as environment variables as kube2iam quickly becomes overloaded and causes failures.

We should look into using iam roles for Kubernetes service accounts as a potential alternative.

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by woodcockr** [comment]
Switching the live repo configuration to use IAM roles for Service Accounts means kube2iam can be deprecated.
