### ISSUE TITLE
New version of terraform provider kubernetes (v1.10) has broken token auth

### ISSUE THREAD

**Issue by NikitaGandhi** [opendatacube/datacube-k8s-eks#127]
This issue is related to Github open issue: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679

**Issue:** 
pipeline started failing with below error:
```
Error: Failed to configure: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
  on modules/setup/main.tf line 4, in provider "kubernetes":
   4: provider "kubernetes" {
```

**temporary fix:**
- pin down provider version to 1.9.0
- or export KUBERNETES_SERVICE_HOST ="" before terraform init

**Comment by woodcockr** [comment]
Fixed in terraform-aws-odc v1.8 candidate
