### ISSUE TITLE
Support 'bring your own database'

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#14]
Make creating a database optional, and create methods to connect to an existing RDS instead.

**Comment by woodcockr** [comment]
I've been looking at the BYOdb options and just wondered what folks thought about the following options:
1. Create an empty database managed by this configuration and an associated db private subnet and security group
2. Create db private subnet and security group  - leave database creation to deployer
3. Do nothing option - entire database setup left to deployer
4. Provide option to create a peering relationship to user provided db, VPC, private, subnet and sg

I'm thinking perhaps the simplest option would be to support 1 and 3+4 and put the different options into the documentation for each scenario (including how to do 2 correctly).

Of these only 4 allows the database setup to be completely separated management wise from the odc-eks deployment which I suspect will be the preferred production deployment but doing 1 makes sense from the "just spin this thing up for me" starting case.

Any other thoughts?

**Comment by roarmstrong** [comment]
I feel that options 1 & 4 are the options worth targeting for an initial release. 2 seems a bit like it could be an extension of option 1, but we need to allow more configuration of the RDS (with sensible defaults) in our Terraform to support options that users might want to use. 3 might be worth targeting later, but I'm not quite sure how common a use case it will be.

**Comment by woodcockr** [comment]
@tom-butler and I had a discussion about BYO db as an option in the ODC community supported cluster. We've decided for easier maintenance and to avoid some terraform side effects associated with optional components we are going to drop support for an optional database and always create one.
This may be revisited if there is demand in future.
