### ISSUE TITLE
Error: Invalid index on Terraform destroy for full infrastructure

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/datacube-k8s-eks#142]
`Error: Invalid index

  on .terraform/modules/odc_eks/infra/modules/database_layer/output.tf line 15, in output "port":
  15:   value      = var.db_instance_enabled ? aws_db_instance.db[0].port : ""
    |----------------
    | aws_db_instance.db is empty tuple

The given key does not identify an element in this collection value.`

**Comment by woodcockr** [comment]
Fairly obvious why as the `aws_db_instance` is destroyed so there is no collection. The output needs to be defined differently so this doesn't occur.

**Comment by woodcockr** [comment]
Fixed on terrafrom-aws-odc branch

**Comment by hildoer** [comment]
> Fairly obvious why as the `aws_db_instance` is destroyed so there is no collection. The output needs to be defined differently so this doesn't occur.

Mind explaining how one might define this output differently? Reading the docs has not helped on this one.

**Comment by woodcockr** [comment]
It's fixed in the new setup (not on master branch) but basically avoid reference to the resource object in outputs. Place the port number into a string and output that string should fix it, default the string to null for the case where the db isn't being created.
