### ISSUE TITLE
Remove DEA specific names

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#15]
Remove DEA specific nomeclature, they should be replace with the more generic ODC - Open Data Cube instead.

**Comment by woodcockr** [comment]
Between us we've removed a lot of the DEA specific names from the repo for the base k8s infrastructure.
There still a lot kicking around in apps and at least one DEA bucket referred to in the infra variables.
I'm not quite sure myself what all of these are referring to so we should have a chat about:

1. Minimum apps in this environment for ODC community deployment
2. What the DEA specific bucket and other apps are so I can decide if I want them in the CSIRO environment as CSIRO will be using the DEA data alongside its own.

**Comment by woodcockr** [comment]
I've noticed any DEA specific remainders of late. Closing this issue.
