### ISSUE TITLE
provide a static IP for application load balancer 

### ISSUE THREAD

**Issue by NikitaGandhi** [opendatacube/datacube-k8s-eks#150]
Implement static IP for ALB:
https://aws.amazon.com/blogs/networking-and-content-delivery/using-static-ip-addresses-for-application-load-balancers/

Background:
Users are accessing the Jupyter hub environment from different places - using their personal Wi-Fi or using corporate network. Many times corporate networks are restricted and not allow traffic outside their network unless white listed. To support such users, we need to implement a static IP for ALB. This can be shared to them if required.

**Comment by woodcockr** [comment]
In reviewing this seemingly stale issue I’m inclined to think this is a more a live deployment configuration choice rather than one for the ODC community support modules?

**Comment by NikitaGandhi** [comment]
> In reviewing this seemingly stale issue I’m inclined to think this is a more a live deployment configuration choice rather than one for the ODC community support modules?

This issue was created during our old infra setup. We can manage it in live repo when required.
