### ISSUE TITLE
Seperate modules into different repositories

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#2]
The EKS and Worker terraform modules should be seperated into different GitHub repos so they can be re-used in more generic platforms.

**Comment by woodcockr** [comment]
@tom-butler I’ve been having a good experience with these terraform modules from [Cloud Posse](https://github.com/cloudposse). The modules are well structured and work well together. Check out [EKS Cluster](https://github.com/cloudposse/terraform-aws-eks-cluster) and [Worker](https://github.com/cloudposse/terraform-aws-eks-workers).

The end result is the same but we can both learn from their patterns or simply use their modules with some minor tweaks.

What do you think?

**Comment by tom-butler** [comment]
I've had a look through those example modules and they look really good. I think it'd be worthwhile using them.

**Comment by woodcockr** [comment]
I'm working on this in a separate repo over on csiroeasi and will merge it in once I know it properly replaces the original piece (that and I had it working in my independently developed eks setup).
@tom-butler I will need to talk with you about organising the merge over. With the current datacube-k8s-eks not working for me I can't do the refactor in place.

**Comment by woodcockr** [comment]
Okay - rejigging our efforts here. We have some other priorities and I suspect how the module setup should work will evolve with that so I'm gonna bump this back into the backlog and we can review it later when the 0.5 release had matured some more

**Comment by woodcockr** [comment]
HI Folks,

I'm pretty happy with the current setup, is this issue still relevant?

**Comment by tom-butler** [comment]
Agreed, lets close this one off.
