### ISSUE TITLE
terraform-aws-odc / 1.8 release 

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#203]
Both CSIRO and us are running the terraform-aws-odc branch in production now, is there anything left to do before we cut the 1.8 release?

**Comment by NikitaGandhi** [comment]
@woodcockr currently uses `csiro-candidate-v1.8` tag for their deployment where as `terraform-aws-odc` has progress a bit (mainly added a odc modules doc and probably updated an example). Which I believe doesn't impact rob.

One last thing which I would like to add before we cut 1.8 release is to enable lifecycle hook to prevent `cognito` delete and `documentation`.

**Comment by woodcockr** [comment]
Was going to ping you guys on this soon, just tied up with late night CEOS teleconferences this week. I was going to tag where we are up to with v1.8-rc2 and test it in my setup and then ask if you were happy to move. Sounds lik eyou are so I will try to complete this today/tomorow

**Comment by NikitaGandhi** [comment]
I think we are good to cut the 1.8 release 👍

**Comment by woodcockr** [comment]
v1.8-rc2 and the subsequent doc commit are tested on my setup. 
Just need one reviewer

**Comment by NikitaGandhi** [comment]
thanks @woodcockr ! As we are the implementer of this release, I would suggest if @tom-butler can review this PR: https://github.com/opendatacube/datacube-k8s-eks/pull/179 and help us close it 👍

**Comment by NikitaGandhi** [comment]
tag: v1.8.0 has been released
