### ISSUE TITLE
Can't save notebook in sandbox

### ISSUE THREAD

**Issue by bellemae** [opendatacube/datacube-k8s-eks#206]
![notebook-error](https://user-images.githubusercontent.com/500884/78329137-9f067480-75cc-11ea-90c4-ef95c59b1b60.PNG)

Getting this error when trying to save notebooks in sandbox

**Comment by NikitaGandhi** [comment]
Thanks belle. Looked at the WAF logs and it's false positive block. We have put a temporary fix so it should work now. We will look into option to implement proper fix. Putting this log for our reference - 

```
[{conditiontype=SQL_INJECTION, location=BODY, matcheddata=[{"type":"notebook","format":"js, /, \n\nsys.path.append(os.path.abs]}]
```
