### ISSUE TITLE
Enable support for external database - e.g. RDS Aurora postgres rather than RDS postgres

### ISSUE THREAD

**Issue by NikitaGandhi** [opendatacube/datacube-k8s-eks#224]
Expose `database_layer` module. This will bring flexibility for our odc infra users to either call our default module to create an RDS or substitute it with their own resources.

**Comment by tom-butler** [comment]
Instead of making this module optional, we could instead expose it to the users, so they can either call our default module to create an RDS or substitute it with their own resources.
