### ISSUE TITLE
cognito module - use for_each rather than count for app_clients

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/datacube-k8s-eks#226]
Cognito module currently uses _count_ for creating each app_client configuration. This is fragile since they actually differ by _name_ not a number. It would be better to use _for_each_ as this will facilitate looking up the configurations by name. See https://www.terraform.io/docs/configuration/resources.html#when-to-use-for_each-instead-of-count

**Comment by tom-butler** [comment]
Good idea, we're currently doing some fairly awkward conversions in the outputs that rely on the order of the apps `value     = module.cognito_auth.client_secrets[1]` 

This sounds like a much better way to work with it.
