### ISSUE TITLE
Upgrade modules to work with terraform > 0.13 and aws provider > 3.0

### ISSUE THREAD

**Issue by NikitaGandhi** [opendatacube/datacube-k8s-eks#244]
Make necessary changes to module as per the Terraform Version 0.13.0 Upgrade guide: https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-13/

Also make any additional fixes to support Terraform AWS Provider Version 3 Upgrade Guide: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade

**Comment by woodcockr** [comment]
I think we should prepare a 1.9.x release with:
- TF 0.13.x, AWS 3.x
- ServiceAccounts with IAM - deprecate kube2iam
- EKS Managed Nodes Groups
- Drop Tiller (Helm2)

Perhaps set up a branch for 1.9.x, do the above changes as feature branches against the 1.9.x branch, then PR it all at once like we did with the 0.12 refactor.
