### ISSUE TITLE
Inconsistent cluster ids

### ISSUE THREAD

**Issue by lbodor** [opendatacube/datacube-k8s-eks#255]
Module `odc_eks` accepts input variable `cluster_id`, but then uses input variables `namespace` and `environment` and the hard-coded suffix `-eks` (via module `odc_eks_label`) to generate the cluster id used to tag public subnets.

So, if a client passes in `some-cluster-id` for cluster_id and `some-namespace` for namespace, then public subnets get tagged with `    "kubernetes.io/cluster/some-namespace-dev-eks" = "shared"` and aren't found by the control plane.

Would you accept a PR to consistently use `var.cluster_id != "" ? var.cluster_id : module.odc_eks_label.id` (via a local binding) as cluster id?

**Comment by NikitaGandhi** [comment]
The fix is release as part of v1.9.1 [here](https://github.com/opendatacube/datacube-k8s-eks/releases/tag/v1.9.1)

**Comment by lbodor** [comment]
Thanks very much.
