### ISSUE TITLE
Define the minimum permissions required to build cluster

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#4]
To make it easier to use this infrastructure we should define the minimum permissions required to create/update the cluster.

There is currently some notes in the readme, but I'll remove them soon as they are focused on kops instead, and are missing key components (eks etc.). A better solution would be providing a .json file that can be used to create a role.

**Comment by jcrattz** [comment]
We (AMA) have found some minimum permissions for creating the cluster through trial and error, so maybe that information can help here.

**Comment by woodcockr** [comment]
I believe this is resolved in the current documentation, though it may well require tweaking from time to time as the capabilities of the ODC base line modules change.
Going to close this now as the issue is stale and a new one created if it the issue arises again.
