### ISSUE TITLE
Replace Helm chart deploy script with terraform

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#5]
If we make use of the terraform helm / kubernetes providers we should be able to remove the bash script that is currently being used to deploy helm charts.

Benefits:
- simpler syntax
- cross platform support
- re-use workspace variables / terraform outputs
- manage state of helm charts

Disadvantages:
- no rollback on failure

Alternatives:
- [flux](https://github.com/weaveworks/flux)
- [helmfile](https://github.com/roboll/helmfile)

**Comment by woodcockr** [comment]
I'll make a start on this, first in my separate repo per other issue comments and eventually in here.

**Comment by tom-butler** [comment]
#20

**Comment by woodcockr** [comment]
I think this issue might be done with #26 and #20.

Can we close this one with those?
