### ISSUE TITLE
Use Private and Public subnets to enhance security

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/datacube-k8s-eks#6]
Most examples of k8s setups I've seen create both public and private subnets, with worker nodes in the private subnet with restricted access.

This should be relatively straightforward to add to this setup. Possibly easily done whilst refactoring the module setup (see #2 )

**Comment by woodcockr** [comment]
If as suggested in #2 we use the Cloud Posse terraform modules as a base for the module refactor then the relevant module is [terraform-aws-dynamic-subnets](https://github.com/cloudposse/terraform-aws-dynamic-subnets). 
One issue is that the private and public subnets have slightly different tags for k8s to know whether or not an external or internal load balancer can be created subnet. The terraform-aws-dynamic-subnets module does support tags but they are common to both subnets. A minor modification will be required to support the separate tags. Very easily achieved.

**Comment by woodcockr** [comment]
I'm working on this in a separate repo over on csiroeasi and will merge it in once I know it properly replaces the original piece (that and I had it working in my independently developed eks setup).
@tom-butler I will need to talk with you about organising the merge over.

**Comment by roarmstrong** [comment]
Implemented in #16
