### ISSUE TITLE
On Destroy, subnets cannot be deleted by Terraform

### ISSUE THREAD

**Issue by roarmstrong** [opendatacube/datacube-k8s-eks#8]
When running `make destroy` terraform cannot correctly delete the subnets in `module.eks.aws_subnet.eks.*` due to each subnet having associated network interfaces. Deleting these network interfaces in the AWS console will allow the subnets to be deleted by Terraform.

**Comment by tom-butler** [comment]
#21

**Comment by roarmstrong** [comment]
Resolved by #21
