### ISSUE TITLE
apply.sh and destroy.sh are formatted as CRLF (DOS) format

### ISSUE THREAD

**Issue by jcrattz** [opendatacube/datacube-k8s-eks#83]
The files `apply.sh` and `destroy.sh` have DOS format (CRLF), so referencing them as `./apply.sh` or `./destory.sh` results in a `No such file or directory` error on Unix. Formatting them as Unix files (LF) should work on both platforms (most importantly Unix).

**Comment by woodcockr** [comment]
git should deal with that automatically if configured correctly.
That said my current checkout is showing Unix LF only.

**Comment by jcrattz** [comment]
It seems my setting for `core.autocrlf` was `true`. I suppose it should be `input`.  Chris and I noticed this, but it seems we forgot about this.

**Comment by woodcockr** [comment]
It gets worse if you use Windows subsystem for linux or linux containers in a windows docker. I just turn it off.
Glad you are all sorted.
